### ISSUE TITLE
Maid Check-In, Cafe Data, Tables, and Waitlist links throw server errors

### ISSUE THREAD

**Issue by MeganeMidori** [maid51play/butler#81]
# Describe the bug

Maid Check-In, Cafe Data, Tables,  and Waitlist links all result in server errors

# To Reproduce
1. Log in at https://fanimaid-butler-staging.herokuapp.com/
2. Click the navigation items in the top menu
3. See the server error

# Expected behavior
Pages should load without errors

# Screenshots
![image](https://user-images.githubusercontent.com/51420500/141033365-e34b671f-6cbc-4fc1-bf54-4c615d6f83b8.png)

# Additional information
 - OS: MacOS
 - Browser: Brave 
 - Version: Version 1.30.89 Chromium: 94.0.4606.81 (Official Build) (x86_64)

# Additional context
This is not reproducible locally, might be some kind of database/migration issue

Stack Traces:

```
2021-11-10T01:33:45.068742+00:00 app[web.1]: Request: GET /reservations?page=1
2021-11-10T01:33:45.068743+00:00 app[web.1]: ** (exit) an exception was raised:
2021-11-10T01:33:45.068743+00:00 app[web.1]:     ** (Postgrex.Error) ERROR 42703 (undefined_column) column r0.barcode_id does not exist
2021-11-10T01:33:45.068744+00:00 app[web.1]: 
2021-11-10T01:33:45.068746+00:00 app[web.1]:     query: SELECT r0."id", r0."name", r0."size", r0."shinkansen", r0."staff", r0."time_waitlisted", r0."time_in", r0."time_out", r0."seat_alone", r0."notes", r0."table_number", r0."inserted_at", r0."updated_at", r0."barcode_id", r0."maid_id" FROM "reservations" AS r0 WHERE (NOT (r0."time_in" IS NULL)) ORDER BY r0."id" LIMIT $1 OFFSET $2
2021-11-10T01:33:45.068747+00:00 app[web.1]:         (ecto_sql 3.1.0) lib/ecto/adapters/sql.ex:605: Ecto.Adapters.SQL.raise_sql_call_error/1
2021-11-10T01:33:45.068747+00:00 app[web.1]:         (ecto_sql 3.1.0) lib/ecto/adapters/sql.ex:538: Ecto.Adapters.SQL.execute/5
2021-11-10T01:33:45.068747+00:00 app[web.1]:         (ecto 3.1.7) lib/ecto/repo/queryable.ex:153: Ecto.Repo.Queryable.execute/4
2021-11-10T01:33:45.068748+00:00 app[web.1]:         (ecto 3.1.7) lib/ecto/repo/queryable.ex:18: Ecto.Repo.Queryable.all/3
2021-11-10T01:33:45.068749+00:00 app[web.1]:         (scrivener_ecto 2.2.0) lib/scrivener/paginater/ecto/query.ex:28: Scrivener.Paginater.Ecto.Query.paginate/2
2021-11-10T01:33:45.068749+00:00 app[web.1]:         (butler 0.0.1) web/controllers/reservation_controller.ex:19: Butler.ReservationController.index/2
2021-11-10T01:33:45.068750+00:00 app[web.1]:         (butler 0.0.1) web/controllers/reservation_controller.ex:1: Butler.ReservationController.action/2
2021-11-10T01:33:45.068750+00:00 app[web.1]:         (butler 0.0.1) web/controllers/reservation_controller.ex:1: Butler.ReservationController.phoenix_controller_pipeline/2
```

```
2021-11-10T01:32:22.276199+00:00 app[web.1]: Request: GET /waitlist?page=1
2021-11-10T01:32:22.276199+00:00 app[web.1]: ** (exit) an exception was raised:
2021-11-10T01:32:22.276200+00:00 app[web.1]:     ** (Postgrex.Error) ERROR 42703 (undefined_column) column r0.barcode_id does not exist
2021-11-10T01:32:22.276200+00:00 app[web.1]: 
2021-11-10T01:32:22.276209+00:00 app[web.1]:     query: SELECT r0."id", r0."name", r0."size", r0."shinkansen", r0."staff", r0."time_waitlisted", r0."time_in", r0."time_out", r0."seat_alone", r0."notes", r0."table_number", r0."inserted_at", r0."updated_at", r0."barcode_id", r0."maid_id" FROM "reservations" AS r0 WHERE (r0."time_in" IS NULL) ORDER BY r0."id" LIMIT $1 OFFSET $2
2021-11-10T01:32:22.276210+00:00 app[web.1]:         (ecto_sql 3.1.0) lib/ecto/adapters/sql.ex:605: Ecto.Adapters.SQL.raise_sql_call_error/1
2021-11-10T01:32:22.276210+00:00 app[web.1]:         (ecto_sql 3.1.0) lib/ecto/adapters/sql.ex:538: Ecto.Adapters.SQL.execute/5
2021-11-10T01:32:22.276210+00:00 app[web.1]:         (ecto 3.1.7) lib/ecto/repo/queryable.ex:153: Ecto.Repo.Queryable.execute/4
2021-11-10T01:32:22.276211+00:00 app[web.1]:         (ecto 3.1.7) lib/ecto/repo/queryable.ex:18: Ecto.Repo.Queryable.all/3
2021-11-10T01:32:22.276211+00:00 app[web.1]:         (scrivener_ecto 2.2.0) lib/scrivener/paginater/ecto/query.ex:28: Scrivener.Paginater.Ecto.Query.paginate/2
2021-11-10T01:32:22.276212+00:00 app[web.1]:         (butler 0.0.1) web/controllers/waitlist_controller.ex:11: Butler.WaitlistController.index/2
2021-11-10T01:32:22.276212+00:00 app[web.1]:         (butler 0.0.1) web/controllers/waitlist_controller.ex:1: Butler.WaitlistController.action/2
2021-11-10T01:32:22.276213+00:00 app[web.1]:         (butler 0.0.1) web/controllers/waitlist_controller.ex:1: Butler.WaitlistController.phoenix_controller_pipeline/2
```

```
2021-11-10T01:31:37.600847+00:00 app[web.1]: Request: GET /tables
2021-11-10T01:31:37.600849+00:00 app[web.1]: ** (exit) an exception was raised:
2021-11-10T01:31:37.600850+00:00 app[web.1]:     ** (Postgrex.Error) ERROR 42P01 (undefined_table) relation "barcodes" does not exist
2021-11-10T01:31:37.600851+00:00 app[web.1]: 
2021-11-10T01:31:37.600854+00:00 app[web.1]:     query: SELECT b0."id", b0."size", b0."inserted_at", b0."updated_at", b0."table_id", b0."table_id" FROM "barcodes" AS b0 WHERE (b0."table_id" = ANY($1)) ORDER BY b0."table_id"
2021-11-10T01:31:37.600855+00:00 app[web.1]:         (ecto_sql 3.1.0) lib/ecto/adapters/sql.ex:605: Ecto.Adapters.SQL.raise_sql_call_error/1
2021-11-10T01:31:37.600855+00:00 app[web.1]:         (ecto_sql 3.1.0) lib/ecto/adapters/sql.ex:538: Ecto.Adapters.SQL.execute/5
2021-11-10T01:31:37.600856+00:00 app[web.1]:         (ecto 3.1.7) lib/ecto/repo/queryable.ex:153: Ecto.Repo.Queryable.execute/4
2021-11-10T01:31:37.600856+00:00 app[web.1]:         (ecto 3.1.7) lib/ecto/repo/queryable.ex:18: Ecto.Repo.Queryable.all/3
2021-11-10T01:31:37.600857+00:00 app[web.1]:         (elixir 1.11.4) lib/enum.ex:1411: Enum."-map/2-lists^map/1-0-"/2
```

```
2021-11-10T01:31:07.129697+00:00 app[web.1]: Request: GET /maids?page=1
2021-11-10T01:31:07.129697+00:00 app[web.1]: ** (exit) an exception was raised:
2021-11-10T01:31:07.129698+00:00 app[web.1]:     ** (Postgrex.Error) ERROR 42703 (undefined_column) column m0.barcode_id does not exist
2021-11-10T01:31:07.129698+00:00 app[web.1]: 
2021-11-10T01:31:07.129701+00:00 app[web.1]:     query: SELECT m0."id", m0."name", m0."status", m0."checked_in_at", m0."inserted_at", m0."updated_at", m0."barcode_id" FROM "maids" AS m0 ORDER BY m0."status" DESC, m0."name" LIMIT $1 OFFSET $2
2021-11-10T01:31:07.129701+00:00 app[web.1]:         (ecto_sql 3.1.0) lib/ecto/adapters/sql.ex:605: Ecto.Adapters.SQL.raise_sql_call_error/1
2021-11-10T01:31:07.129701+00:00 app[web.1]:         (ecto_sql 3.1.0) lib/ecto/adapters/sql.ex:538: Ecto.Adapters.SQL.execute/5
2021-11-10T01:31:07.129702+00:00 app[web.1]:         (ecto 3.1.7) lib/ecto/repo/queryable.ex:153: Ecto.Repo.Queryable.execute/4
2021-11-10T01:31:07.129702+00:00 app[web.1]:         (ecto 3.1.7) lib/ecto/repo/queryable.ex:18: Ecto.Repo.Queryable.all/3
2021-11-10T01:31:07.129703+00:00 app[web.1]:         (scrivener_ecto 2.2.0) lib/scrivener/paginater/ecto/query.ex:28: Scrivener.Paginater.Ecto.Query.paginate/2
2021-11-10T01:31:07.129703+00:00 app[web.1]:         (butler 0.0.1) web/controllers/maid_controller.ex:35: Butler.MaidController.index/2
2021-11-10T01:31:07.129703+00:00 app[web.1]:         (butler 0.0.1) web/controllers/maid_controller.ex:1: Butler.MaidController.action/2
2021-11-10T01:31:07.129704+00:00 app[web.1]:         (butler 0.0.1) web/controllers/maid_controller.ex:1: Butler.MaidController.phoenix_controller_pipeline/2
```

**Comment by MeganeMidori** [comment]
ran `mix ecto.migrate` in the servers and all is well again :)
